/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /** Delete Analysis */
        delete: operations["delete_analysis_api_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Stream */
        post: operations["analyze_stream_api_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Id */
            id?: number | null;
            /** Brand */
            brand: string;
            /** Domain */
            domain?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Visibility Score
             * @description Aggregate score, 0..100.
             */
            visibility_score: number;
            /**
             * Mention Rate
             * @description Fraction of queries that mentioned the brand.
             */
            mention_rate: number;
            /** Recommendation Rate */
            recommendation_rate: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Results */
            results: components["schemas"]["MentionResult"][];
        };
        /** AnalysisSummary */
        AnalysisSummary: {
            /** Id */
            id?: number | null;
            /** Brand */
            brand: string;
            /** Domain */
            domain?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Visibility Score
             * @description Aggregate score, 0..100.
             */
            visibility_score: number;
            /**
             * Mention Rate
             * @description Fraction of queries that mentioned the brand.
             */
            mention_rate: number;
            /** Recommendation Rate */
            recommendation_rate: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Brand
             * @example Yolando
             */
            brand: string;
            /**
             * Domain
             * @example yolando.ai
             */
            domain?: string | null;
            /**
             * Category
             * @description Market category, e.g. 'generative engine optimization tools'.
             * @example AI brand-visibility tools
             */
            category?: string | null;
            /**
             * Aliases
             * @description Alternate spellings/names to also count as a mention.
             */
            aliases?: string[];
            /**
             * Prompts
             * @description Override the default buyer-intent prompts.
             */
            prompts?: string[] | null;
            /**
             * Models
             * @description Subset of provider names to query (default: all available).
             */
            models?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MentionResult */
        MentionResult: {
            /** Prompt */
            prompt: string;
            /** Model */
            model: string;
            /** Mentioned */
            mentioned: boolean;
            /** Recommended */
            recommended: boolean;
            /**
             * Rank
             * @description 1-based position when the answer is a ranked list.
             */
            rank?: number | null;
            /** Excerpt */
            excerpt?: string | null;
            /**
             * Score
             * @description Per-(prompt, model) visibility score, 0..1.
             */
            score: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cached */
            cached: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_api_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_api_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stream_api_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
